global with sharing class SomeClass {
    public Integer int1;
    protected String str1;
    private Integer int2;
    global String str2;
    double dbl1;
    Integer int3;
    protected String str3;
    Integer int4;
    global String str4;
    global double dbl2;

	public SomeClass(Integer int1, String str1, Integer int2, String str2,double dbl1,Integer int3, String str3,Integer int4, String str4, double dbl2){
        this.int1 = int1;
        this.str1 = str1;
        this.int2 = int2;
        this.str2 = str2;
        this.dbl1 = dbl1;
        this.int3 = int3;
        this.str3 = str3;
        this.int4 = int4;
        this.str4 = str4;
        this.dbl2 = dbl2;
	}




}